macro (add_cxx_compiler_flags)
    foreach (flag ${ARGV})
        set (all_flags "${all_flags} ${flag}")
    endforeach ()
endmacro ()

function(add_gcc_flags)
        add_cxx_compiler_flags (-g)
        add_cxx_compiler_flags (-O0)
        add_cxx_compiler_flags (-Wall)
        add_cxx_compiler_flags (-fprofile-arcs)
        add_cxx_compiler_flags (-ftest-coverage)
        add_cxx_compiler_flags (-pedantic)
        add_cxx_compiler_flags (-Wall)
        add_cxx_compiler_flags (-Wcast-align)
        add_cxx_compiler_flags (-Wctor-dtor-privacy)
        add_cxx_compiler_flags (-Wdisabled-optimization)
        add_cxx_compiler_flags (-Wformat=2)
        add_cxx_compiler_flags (-Winit-self)
        add_cxx_compiler_flags (-Wlogical-op)
        add_cxx_compiler_flags (-Wmissing-declarations)
        add_cxx_compiler_flags (-Wmissing-include-dirs)
        add_cxx_compiler_flags (-Wnoexcept)
        add_cxx_compiler_flags (-Wold-style-cast)
        add_cxx_compiler_flags (-Woverloaded-virtual)
        add_cxx_compiler_flags (-Wredundant-decls)
        add_cxx_compiler_flags (-Wsign-conversion)
        add_cxx_compiler_flags (-Wsign-promo)
        add_cxx_compiler_flags (-Wstrict-null-sentinel)
        add_cxx_compiler_flags (-Wstrict-overflow=5)
        add_cxx_compiler_flags (-Wswitch-default)
        add_cxx_compiler_flags (-Wundef)
        add_cxx_compiler_flags (-Wno-unused)
        set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${all_flags}" PARENT_SCOPE)
endfunction()
